name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update
        sudo apt-get install unzip libtool curl cmake gperf gawk flex bison nano \
        git python-docutils gettext automake autopoint texinfo build-essential \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    - name: Clone source code
      run: |
        sudo git clone --depth=1 https://github.com/trublemaker/rt-n56u.git -b New3 /opt/rt-n56u
        sudo rm -rf opt/rt-n56u/toolchain-mipsel/
        sudo git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/pd
        sudo mv -f /opt/pd/toolchain-mipsel opt/rt-n56u
        sudo chmod u+x opt/rt-n56u/toolchain-mipsel/*
        cd opt/rt-n56u/toolchain-mipsel
        sudo ./dl_toolchain.sh
        sudo mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        sudo ./clear_tree
        fakeroot ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
